### PR TITLE
fix(timeout): compare creation time to now - timeout

### LINKED ISSUE #264: Potential Logic Issue in GetLocksOlderThan Methods Data Retrieval.
The [GetLocksOlderThan ](https://github.com/nextcloud/files_lock/blob/v27.0.4/lib/Db/LocksRequest.php#L147)(int $timeout) method cannot retrieve data. The 149 lines of this method are the conditions for data query, which cannot retrieve data. Because "$timeout" is the set time (in minutes), and the creation field in the files_lock data table is a unix timestamp, a 10 digit integer number$ Timeout * 60 is impossible to exceed the value of the creation field, which means that data cannot be retrieved. Is there a problem with this logic.

### PR DESCRIPTION
**Pull request by max-nextcloud**
Fixes #264.

### CODE REVIEW

**Comment by max-nextcloud** [comment]
Haven't been able to test this yet myself.

**Comment by juliusknorr** [comment]
Please also check if we can cover this with tests, we have something around expiry in https://github.com/nextcloud/files_lock/blob/16d856fb5b36ade8308f683533dbe768705582b6/tests/Feature/LockFeatureTest.php#L183-L205 at least, but maybe that test does not cover it properly

**Comment by juliusknorr** [comment]
Makes sense code wide 👍

**Comment by max-nextcloud** [comment]
> Please also check if we can cover this with tests

I added an assertion to the test but it's failing. Maybe we can investigate together in the coming days. Locally the test fails for me before it even gets to this point. Actually I think I will turn this into two tests.

**Comment by max-nextcloud** [comment]
@juliusknorr I think the failing static test is somehow a sideeffect of adding logging to lib/Service/LockService.php - but I don't understand how that would come about.
Could you have another look?

File: lib/Service/LockService.php [hunk 1]
```diff
@@ -388,4 +389,20 @@ private function propagateEtag(LockContext $lockContext): void {
...
+	private function notice(string $message, bool $trace = false, array $serializable = []) {
+		$opts = ['app' => 'files_lock'];
+		if ($trace) {
+			$opts['exception'] = new HintException($message, json_encode($serializable));
+		} elseif (!empty($serializable)) {
+			$message .= ' -- ' . json_encode($serializable);
+		}
+		$this->logger->notice('[notice] ' . $message, $opts);
+	}
+
```
Comment (max-nextcloud) [inline lib/Service/LockService.php:407]: Mostly took this from the `TLogger` trait - but i don't know how the `Psr\Log\LoggerInteface` works:
* do we still need to prefix the message with `[notice] `?
* do the $opts have the same effect they used to have in the `TLogger`?

**Review by juliusknorr — APPROVED** [review]

**Comment by Jerome-Herbinet** [comment]
Can someone explain to me in human language what this PR corrects (describe the problem encountered by the end user, before fixing it)? Thanks by advance.

**Comment by max-nextcloud** [comment]
> Can someone explain to me in human language what this PR corrects (describe the problem encountered by the end user, before fixing it)

There was no impact on the end user as far as I can tell. Locks that had expired were not removed from the database. But since expired locks are not taken into account that had no effect other than old lock records piling up.
