### PR TITLE
fix: Chunk db query for locks by file id

### LINKED ISSUE #120: Does not work with Oracle in bigger setups
```json
{
  "reqId": "IMTXI0EnGJGi1Coph1XG",
  "level": 3,
  "time": "2023-02-24T09:06:18+00:00",
  "remoteAddr": "2a01…",
  "user": "…",
  "app": "core",
  "method": "PROPFIND",
  "url": "/remote.php/dav/files/…/…",
  "message": "More than 1000 expressions in a list are not allowed on Oracle.",
  "userAgent": "Mozilla/5.0 (Windows) mirall/3.7.3stable-Win64 (build 20230209) (Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64 OsArchitecture: x86_64)",
  "version": "25.0.4.0",
  "exception": {
    "Exception": "Doctrine\\DBAL\\Query\\QueryException",
    "Message": "More than 1000 expressions in a list are not allowed on Oracle.",
    "Code": 0,
    "Trace": [
      {
        "file": "…/apps/files_lock/lib/Tools/Db/ExtendedQueryBuilder.php",
        "line": 1019,
        "function": "execute",
        "class": "OC\\DB\\QueryBuilder\\QueryBuilder",
        "type": "->",
        "args": []
      },
      {
        "file": "…/apps/files_lock/lib/Db/LocksRequestBuilder.php",
        "line": 138,
        "function": "getRows",
        "class": "OCA\\FilesLock\\Tools\\Db\\ExtendedQueryBuilder",
        "type": "->",
        "args": [
          [
            [
              "OCA\\FilesLock\\Db\\LocksRequest"
            ],
            "parseLockSelectSql"
          ]
        ]
      },
      {
        "file": "…/apps/files_lock/lib/Db/LocksRequest.php",
        "line": 127,
        "function": "getLocksFromRequest",
        "class": "OCA\\FilesLock\\Db\\LocksRequestBuilder",
        "type": "->",
        "args": [
          [
            "OCA\\FilesLock\\Db\\CoreQueryBuilder"
          ]
        ]
      },
      {
        "file": "…/apps/files_lock/lib/Service/LockService.php",
        "line": 140,
        "function": "getFromFileIds",
        "class": "OCA\\FilesLock\\Db\\LocksRequest",
        "type": "->",
        "args": [
          [
            "6180204",
            "6180206",
            "6180203",
            "6181016",
            "6180752",
            "And 1322 more entries, set log level to debug to see all entries"
          ]
        ]
      },
      {
        "file": "…/apps/files_lock/lib/DAV/LockPlugin.php",
        "line": 86,
        "function": "getLockForNodeIds",
        "class": "OCA\\FilesLock\\Service\\LockService",
        "type": "->",
        "args": [
          [
            "6180204",
            "6180206",
            "6180203",
            "6181016",
            "6180752",
            "And 1322 more entries, set log level to debug to see all entries"
          ]
        ]
      },
      {
        "file": "…/apps/files_lock/lib/DAV/LockPlugin.php",
        "line": 97,
        "function": "cacheDirectory",
        "class": "OCA\\FilesLock\\DAV\\LockPlugin",
        "type": "->",
        "args": [
          [
            "OCA\\DAV\\Connector\\Sabre\\Directory"
          ]
        ]
      },
      {
        "file": "…/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "customProperties",
        "class": "OCA\\FilesLock\\DAV\\LockPlugin",
        "type": "->",
        "args": [
          [
            "Sabre\\DAV\\PropFind"
          ],
          [
            "OCA\\DAV\\Connector\\Sabre\\Directory"
          ]
        ]
      },
      {
        "file": "…/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 1052,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "propFind",
          [
            [
              "Sabre\\DAV\\PropFind"
            ],
            [
              "OCA\\DAV\\Connector\\Sabre\\Directory"
            ]
          ]
        ]
      },
      {
        "file": "…/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 984,
        "function": "getPropertiesByNode",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          [
            "Sabre\\DAV\\PropFind"
          ],
          [
            "OCA\\DAV\\Connector\\Sabre\\Directory"
          ]
        ]
      },
      {
        "file": "…/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 1662,
        "function": "getPropertiesIteratorForPath",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "files/…/…",
          [
            "{DAV:}resourcetype",
            "{DAV:}getlastmodified",
            "{DAV:}getcontentlength",
            "{DAV:}getetag",
            "{http://owncloud.org/ns}size",
            "And 15 more entries, set log level to debug to see all entries"
          ],
          1
        ]
      },
      {
        "file": "…/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 1647,
        "function": "writeMultiStatus",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          [
            "Sabre\\Xml\\Writer",
            [],
            "/remote.php/dav/",
            [
              "d",
              "s",
              "oc",
              "nc"
            ],
            []
          ],
          [
            "Generator"
          ],
          false
        ]
      },
      {
        "file": "…/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
        "line": 346,
        "function": "generateMultiStatus",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          [
            "Generator"
          ],
          false
        ]
      },
      {
        "file": "…/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "httpPropFind",
        "class": "Sabre\\DAV\\CorePlugin",
        "type": "->",
        "args": [
          [
            "Sabre\\HTTP\\Request"
          ],
          [
            "Sabre\\HTTP\\Response"
          ]
        ]
      },
      {
        "file": "…/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 472,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "method:PROPFIND",
          [
            [
              "Sabre\\HTTP\\Request"
            ],
            [
              "Sabre\\HTTP\\Response"
            ]
          ]
        ]
      },
      {
        "file": "…/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 253,
        "function": "invokeMethod",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          [
            "Sabre\\HTTP\\Request"
          ],
          [
            "Sabre\\HTTP\\Response"
          ]
        ]
      },
      {
        "file": "…/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 321,
        "function": "start",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "…/apps/dav/lib/Server.php",
        "line": 360,
        "function": "exec",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "…/apps/dav/appinfo/v2/remote.php",
        "line": 35,
        "function": "exec",
        "class": "OCA\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "…/remote.php",
        "line": 171,
        "args": [
          "…/apps/dav/appinfo/v2/remote.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "…/lib/private/DB/QueryBuilder/QueryBuilder.php",
    "Line": 264,
    "message": "More than 1000 expressions in a list are not allowed on Oracle.",
    "query": "SELECT `l`.`id`, `l`.`user_id`, `l`.`file_id`, `l`.`token`, `l`.`creation`, `l`.`type`, `l`.`ttl`, `l`.`owner` FROM `*PREFIX*files_lock` `l` WHERE `l`.`file_id` IN (:dcValue1)",
    "exception": {},
    "CustomMessage": "More than 1000 expressions in a list are not allowed on Oracle."
  }
}
```

### PR DESCRIPTION
**Pull request by juliushaertl**
fixes #120

### CODE REVIEW

File: lib/Service/LockService.php [hunk 1]
```diff
@@ -137,10 +137,13 @@ public function getLockForNodeIds(array $nodeIds): array {
...
 		}
-		$newLocks = $this->locksRequest->getFromFileIds($locksToRequest);
-		foreach ($locksToRequest as $lockId) {
-			$this->lockCache[$lockId] = false;
+
+		$newLocks = [];
+		while ($fileIds = array_splice($locksToRequest, 0, 1000)) {
+			$newLocks[] = $this->locksRequest->getFromFileIds($fileIds);
 		}
+		$newLocks = array_merge(...$newLocks);
```
Comment (marcelklehr) [inline lib/Service/LockService.php:145]: What happened to `$this->lockCache[$lockId] = false;`?

Comment (juliushaertl) [reply lib/Service/LockService.php:145]: This is overwritten when iterating over the new locks again anways below.
